### PR TITLE
DOP-3456: Update font sizes

### PR DESCRIPTION
**Pull request by rayangler**
### Stories/Links:

DOP-3456

### Screenshots (optional):

**"Responses" components with 16px.**
dop-3456-responses

**Right side panel components with 13px.**
dop-3456-side-panel

**Updated page example**
dop-3456-updated-page

### Notes:
* Fonts were updated according to the designs specified in the [Figma file](https://www.figma.com/file/PctpWXNmlv0khZahanOsU7/FY22-New-Brand?node-id=1457%3A18432&t=GHFZRPAvM8TDr1S4-0).
* The "Responses" components in the main column should be 16px like the rest of the main body content. This should be similar to what's in production right now.
* Components on the right side panel should use 13px. This is something that was intentionally changed but accidentally forgotten about in production.
* Updates dropdown labels ("Content type", "Example") on the righthand column to not be absolutely positioned.

### CODE REVIEW

**Review by mmeigs — COMMENTED** [review]
Looks great. But I can't help but notice the components on the right hand panel still have an odd spacing that isn't seen in our current Redoc. I believe it might just boil down to the "title" of the property being `position: absolute` when it doesn't need to be. An example is the Content type above the application/json value. If the span holding "Content type" has `position:absolute` taken away then it seems to move into the normal flow that I'm used to seeing. 

---- EDIT: okay, looking at our prod site now and this is the same spacing actually. However, it just can't be right!! We must be overriding it somewhere. I can look tomorrow for it!

Lots of words to say one simple thing we can account for! 
Screen Shot 2023-01-18 at 4 46 24 PM
vs
Screen Shot 2023-01-18 at 4 52 30 PM

**Review by mmeigs — APPROVED** [review]
Btw, approving this because my comment was not blocking!! It matches our prod so, I'm good with this. We can either work on that spacing now or later, doesn't matter to me. So, feel free to merge!

**Comment by mmeigs** [comment]
> Looks great. But I can't help but notice the components on the right hand panel still have an odd spacing that isn't seen in our current Redoc. I believe it might just boil down to the "title" of the property being `position: absolute` when it doesn't need to be. An example is the Content type above the application/json value. If the span holding "Content type" has `position:absolute` taken away then it seems to move into the normal flow that I'm used to seeing.
> 
> ---- EDIT: okay, looking at our prod site now and this IS the same spacing actually. However, it just can't be right!! We must be overriding it somewhere. I can look tomorrow for it!
> 

So, I found that it all stems from `Redoc` itself under the styled span element called `DropdownLabel`. Then I went to the live demo on Redocly's site... and they have the same spacing!! Just noting it here for the future that it is as it "should" be, but I just don't understand having a label be half in/out of a colored div.

**Comment by rayangler** [comment]
@mmeigs Oh, gotcha. Thanks for looking into this! Based on the Figma, it does seem like the intention is to separate "Content type" away from being in between the div. I'll add it on to this PR since it *should* be small enough of a change and shouldn't impact much else.

I'll request for re-review when ready!

**Comment by rayangler** [comment]
@mmeigs - requesting a re-review with the updated dropdown labels. Added this image to the description as well, but here's what it looks like:

dop-3456-updated-page

**Pull request merged**
